### ISSUE TITLE
Publishing generated trajectories in a visualizable format

### ISSUE THREAD

**Issue by hy565** [mrsd16teamd/loco_car#3]
right now the generated trajectories are a custom message type - an array of nav_msgs::Odometry. Need a separate publisher to publish them one by one in a loop for visualizing in Rviz.

**Comment by hy565** [comment]
@aumj in traj_client.cpp line 131, why are these push backed twice?

`    end_goal.traj.commands.push_back(control_msg);
    end_goal.traj.commands.push_back(control_msg);
    end_goal.traj.states.push_back(cur_state_);
    end_goal.traj.states.push_back(cur_state_);`

Also, why are we adding the current state estimate to the traj.states? shouldn't it contained the desired states instead of the estimated state?

**Comment by aumj** [comment]
Resolved duplicate push backs and predicting desired trajectory. Is visualization for ramp still not working?

**Comment by hy565** [comment]
can you verify that the goal state being printed out is legit when running the ramp? last time it was increasing exponentially right?

**Comment by aumj** [comment]
Yes, that bug was introduced when mode switching was implemented. That's fixed now.
