### ISSUE TITLE
Move_base /odom topic input source 

### ISSUE THREAD

**Issue by nickchuang** [mrsd16teamd/loco_car#5]
Hi Sir,

![nav_launch_rqt_graph](https://user-images.githubusercontent.com/29449379/28314400-09204bbc-6bed-11e7-92ce-00cb99e26049.png)

Base on attached file, I can't see ekf output odometry/filtered topic relationship with move_base input odeom. 

Could you tell me about move_base topic /odom input source?

**Comment by kazuotani14** [comment]
I interpreted your question as: "Why isn't there an arrow between the odom topic and ekf_state_estimator node?" If this is not correct, please clarify.
The /odom topic is there for convenience - the transform between map and odom are also published on the TF tree. ekf_state_estimator looks at the TF tree (/tf)to get the raw odom information, which it then filters/merges with other sources to provide a filtered estimate.

**Comment by jason1pan** [comment]
Thank for your feedback.

Does the ekf_state_estimator node is proved tf information for global_planner?
So base on Navigation architecture.
About Local_planner? Which node provide to source for /odom node?

**Comment by kazuotani14** [comment]
It seems like most of your confusion comes from the navigation and robot_localization stacks, I think you might find better help from their documentation: [Navigation](http://wiki.ros.org/navigation/Tutorials), [Robot Localization](http://docs.ros.org/kinetic/api/robot_localization/html/index.html).
We have a couple links and pointers in our wiki as well.

**Comment by nickchuang** [comment]
Base on ekf.png file. ekf_state_estimater node need to output odom  data provide to move_base. Our question is run nav.lunch file to execute rqt_graph can't see odometry provide data to odom. 
![ekf](https://user-images.githubusercontent.com/29449379/28355927-a251b054-6c98-11e7-8f99-39b24781d32a.png)

**Comment by kazuotani14** [comment]
ekf_state_estimator publishes a transform between map and odom, which you can't see on rqt_graph.
This link might be helpful for understanding the role of each node:
http://answers.ros.org/question/222567/specific-odom-frame-responsibility/

**Comment by nickchuang** [comment]
Hi Kazu Otani

As my understanding, the navigation stack requires that odometry information be published using tf and nav_msg/odometry message.

There are two issues be confused me:

The first, I did not see ekf_state_estimator node publish tf map->odom in my tf frame tree. The tf map->odom is always published by /amcl. I don’t know EKF is working properly or not. Below is my tf frame tree.
![tf_frames](https://user-images.githubusercontent.com/29449379/28524058-9dec1cf8-70b1-11e7-9f5d-df48d4bd3944.png)

I would appreciate it if you could share your loco tf frame tree.

The second, nav_msg/odometry message not be published to move_base from ekf_state_estimator node or any odom source, like as VESC odom in loco car project. Is it correct?


If navigation stack just get the odometry information from tf only and not get  nav_msg/odometry message, the self-driving can work or not?

(I assumed that tf information is correct and sample rate is high, for example , use high scan rate Lidar)

**Comment by HappySamuel** [comment]
To: Nick Huang

I have been using their code, this is my simple modification version of it. 
Node_graph
[lococar_obstacle_avoidance_node_graph.pptx](https://github.com/mrsd16teamd/loco_car/files/1175401/lococar_obstacle_avoidance_node_graph.pptx)

Inside the node_graph you can see that you have to change the navigation package's "/odom" topic into "/odometry/filtered", in order to  receive the topic message from ekf_state_estimator. 

While the question you ask about the tf tree, since the amcl has published the transform for "map -> odom", ekf_state_estimator has subscribed the transform from /tf, hence it knows all the relationship between all frames.

[modified_lococar_tf_frames.pdf](https://github.com/mrsd16teamd/loco_car/files/1175413/modified_lococar_tf_frames.pdf)

Transform "map -> odom", "base_link -> laser", "odom -> base_link", "base_link -> imu"

**Comment by kazuotani14** [comment]
Thanks for the clarification @HappySamuel. Sorry for the confusion, the ekf_state_estimate is something we added after we transitioned from using move_base to using our own controller (ilqr_loco) - this is why move_base is not configured to use odometry/filtered.

**Comment by nickchuang** [comment]
Hi Kazu Otani and HappySamuel

Thanks for your feedback. I really appreciate your help and share your data and information to me.
Let me have a clear of this concept.
