### ISSUE TITLE
What firmware version I need to load to teensy board?

### ISSUE THREAD

**Issue by terrytzeng** [mrsd16teamd/loco_car#6]
Hi Loco  professional,
Excuse me for how to select teensy firmware version in non using VESC(Just only use teensy to control ESC and Servo). I find teensy FW in loco car code base, but I don't know which version I need for navigation.
Loco car teensy FW list:
1. MST_steering_analogWrite.ino
2. MST_teensy.ino
3. real_mapping.ino
4. realmaptwist_2S_Lipo.ino
5. stock_ack_subscriber_killswitch_timeout.ino

Use hardware environment:
1. traxxas 1/10 car
2. Jetson TX1
3. Teensy
... etc

BR, Terry

**Comment by hy565** [comment]
you can use the _MST_teensy.ino_  . This will listen for geometry_msgs/Twist from ROS and map it to PWM commands on the esc_pin and servo_pin, which should be hooked up to your traxxas's ESC and steering servo. You'll have to take note of the steering/throttle limits specific to your traxxas and edit the values accordingly to get an accurate mapping.

**Comment by terrytzeng** [comment]
Hi hy565,

Thanks for your feedback information and suggestion.

BR, Terry
